### ISSUE TITLE
Feature Request: make `primaryKey` optional in `createKeyPair` method

### ISSUE THREAD

**Issue by MiguelMedeiros** [slashtags/keychain#1]
Hey @Nuhvi ,

I've been using your library and it's been great for my needs. However, I have a feature request to enhance the `createKeyPair` method.

#### Current Behavior:
Right now, the `primaryKey` argument is required when using the `createKeyPair` method:

```typescript
createKeyPair(primaryKey: Uint8Array, name?: string | Uint8Array): {
    publicKey: any;
    secretKey: any;
}
```

#### Suggested Enhancement:
Would it be possible to make `primaryKey` optional, and generate a random one if it is not provided? For example:

```typescript
createKeyPair(primaryKey?: Uint8Array, name?: string | Uint8Array): {
    publicKey: any;
    secretKey: any;
}
```

In the implementation, a random `primaryKey` could be generated like so (very naive solution!):

```typescript
if (!primaryKey) {
  primaryKey = randomBytes(32);
}
```

#### Use Case:
This would be particularly useful for scenarios where the user does not have a preference for a specific `primaryKey`, and would trust the library to generate a secure, random one.

I think this feature would make the library even more user-friendly. Looking forward to your thoughts.

**Comment by Nuhvi** [comment]
@MiguelMedeiros I dislike that because the `keychain` is supposed to encourage people to have a `primaryKey` that they store somewhere, hopefully even generated it from real Bitcoin seed that they care about, instead of making disposable keypairs. That is the purpose of this repo and how it is used in Bitkit.

I especially resist this change, since the web relay already allow you to [generate random keyPair](https://github.com/slashtags/web-relay/blob/main/lib/client/index.js#L511).

**Comment by MiguelMedeiros** [comment]
Thanks for the quick reply and for explaining why `primaryKey` is set up the way it is. 
Makes sense, especially considering how it's used in Bitkit.

No worries, I'll go ahead and close the issue.
